package injunction.detector

import injuction.detector.InjunctionDetector
import spock.lang.Specification

class InjunctionDetectorTest extends Specification {

    InjunctionDetector detector

    void setup() {
        detector = new InjunctionDetector()
    }

    def "Detector can find simple not phrases"() {
        expect:
        detector.isInjuction("You don’t have time for distractions")

    }

    def "Detector can works on a wide variety of phrases"(String testText) {
        expect:
        detector.isInjuction(testText)

        where:
        testText << [
                "I will never read this",
                "I do not like reading this",
                "I'm not contradicting you",
                "It's not the best for you",
                "This isn't working",
                "You don’t have time for distractions",
                "They don’t let you play small",
                "I don’t wanna stop",
                "Don’t stop me at all",
                "I realize it didn’t serve me",
                "I’m not ready",
                "You can’t handle it",
                "You don’t have to do this by yourself",
                "You aren’t worthy",
                "You will not regret it",
                "Don’t forget it",
                "Social media is not the only way to promote yourself",
                "We can, they can’t",
                "I didn’t understand",
                "I don’t understand it",
                "Don’t panic",
                "Don’t work on Mondays and Fridays",
                "They won’t kill you",
                "We can’t even think about it",
                "I didn’t want to confront",
                "You don’t have an assistant",
                "Too many options, not to worry about that",
                "I don’t want to be on the stage",
                "The trick is not to get attached to it",
                "I don’t care how scary it is",
                "Tell her, don’t unmute herself",
                "I don’t want to come home and cook every night",
                "Don’t wait for the perfect time",
                "Don’t be afraid",
                "Don’t let that stop you",
                "I don’t care",
                "Don’t worry, you’re going to love them",
                "Don’t every ask for permission",
                "They are not bad people",
                "Don’t blame them",
                "You don’t have to have it all figured out",
                "We don’t think of ourselves as old as we are",
                "Can’t wait to start",
                "We are not doing that",
                "I may have old age, I’m not that old",
                "I didn’t expect it to come up",
                "I don’t share secrets",
                "I don’t follow all the way through",
                "Where it’s not working perfectly",
                "That can not be taken away",
                "Don’t let them stop you",
                "It’s not there to make you feel bad",
                "It’s not that difficult to do",
                "Find people that won’t judge you",
                "You can’t miss it",
                "We don’t need to apologize",
                "I don’t want to live in LA",
                "I don’t want to live that crazy life",
                "Don’t beat yourself up",
                "I didn’t want to be in this marriage",
                "I never should have got marry",
                "I don’t want you to feel left out",
                "It doesn’t matter",
                "You don’t have to have experience to be this",
                "It doesn’t really matter",
                "Don’t let that bother you",
                "They don’t need to leave that company",
                "Don’t let it stop you",
                "Don’t let your intimation get in the way of your dreams",
                "She didn’t want to be a mortgage broker",
                "It didn’t work the way I thought it would",
                "You don’t have to do that",
                "Facilitate not only understanding",
                "Don’t talk to her on the phone",
                "I don’t believe in coincidences",
                "He didn’t want to go the grocery store",
                "Don’t let it run you",
                "You can’t go that way",
                "His pump is not working",
                "Don’t look at me",
                "He doesn’t know what he’s going to do",
                "You can’t beat me",
                "Don’t wait too long",
                "It doesn’t produce the results",
                "Don’t try to cram these teachings down their throat",
                "You can’t put a price on living your best life",
                "You’re not on the fence",
                "It didn’t happen overnight",
                "It’s not a contest",
                "We don’t want to leave you hanging",
                "You’re not willing to wait",
                "It wasn’t going anywhere",
                "Why didn’t I do this sooner",
                "Don’t let all your head stuff to get in the way",
                "You can’t lose",
                "I don’t feel guilty",
                "I don’t need people for wisdom",
                "We haven’t gotten there yet",
                "You can’t mess up",
                "We’re not going to keep you",
                "It doesn’t have to be this way",
                "We don’t want that to happen",
                "We can’t wait to see your vision come to life",
                "Our parents aren’t always right",
                "Most of you are not in danger of that",
                "Not to get overwhelmed",
                "Don’t start there",
                "You don’t have to stay in the cell you are in",
                "Our self talk is not accurate",
                "It doesn’t have to be a big thing",
                "Don’t let it stop you",
                "Don’t overthink it",
                "It’s not about the stuff",
                "Don’t pursue chaos",
                "Don’t go back to history that has made you",
                "Make some changes, not to go back to old self",
                "I don’t want to go back to that toxic workplace",
                "Don’t eat it everyday",
                "Habits that are not serving your goals",
                "Don’t limit yourself working with the youth",
                "I kid you not",
                "I don’t like showing my body",
                "If it doesn’t work, its fine",
                "Don’t send God to voicemail",
                "The video is not working",
                "We are going to do an exercise we were not planning to do",
                "Right now I can’t do that",
                "It’s cut off not one more penny",
                "Don’t interrupt them",
                "I don’t want to participate anymore",
                "Do not let if run you",
                "Impossible is an opinion not a fact",
                "I can’t get enough of this",
                "We didn’t know each other that well",
                "I didn’t have anything planned",
                "You don’t create abundance by focusing on debt",
                "You will not get better by focusing on problems",
                "If you don’t do that then you keep the habit",
                "It doesn’t produce a better result",
                "Don’t go breaking my heart",
                "You’re not in traffic, you are traffic",
                "Forget it, it doesn’t serve you",
                "Prince Charming is not coming",
                "The wheels don’t fall off",
                "They didn’t do anything because of that people died",
                "We don’t complain about gravity",
                "I can’t even put my elbows together",
                "If you haven’t read his book I recommend it",
                "We don’t need the money we donated it to charity",
                "You don’t care about me",
                "I don’t think your project is important",
                "I just don’t have the time",
                "I’m not going to work on the book until the pandemic is over",
                "Often you don’t feel like a late night snack",
                "I can’t find my phone",
                "Don’t buy a new phone",
                "Anybody can find 10 minutes, I don’t care",
                "We don’t have to give excuses",
                "27 pens that don’t work",
                "Do it in the next minute, you don’t need to do it all",
                "I don’t check emails/texts until after I’ve treadmill for 15-30 minutes",
                "Don’t use my left arm",
                "If you don’t know you can start with this",
                "It doesn’t mean it will show up",
                "This isn’t working",
                "I’m not on commission",
                "When you don’t back down",
                "Don’t miss out on it",
                "Don’t worry",
                "You are not your mind",
                "It doesn’t want to get us into trouble",
                "Don’t judge yourself",
                "Ain’t nobody gonna come and save us",
                "Carry that’s not yours",
                "I should not be depressed",
                "Don’t give up",
                "Don’t stop reaching",
                "Don’t turn away from yourself",
                "We don’t have to wait for a catastrophe",
                "I don’t feel like dying",
                "I don’t want that",
                "It’s not selfish",
                "Don’t judge yourself",
                "I’m not contradicting you",
                "It’s not the best for you",
                "It will be not self destructive",
                "It’s not the right time",
                "It’s okay not to be afraid",
                "I can’t do this anymore",
                "Don’t let me do"
        ]
    }

    def "Detector can find simple should phrases"(String testText) {
        expect:
        detector.isInjuction(testText)

        where:
        testText << [
                "I should really read this",
                "I shouldn't do this",
                "You should listen to me",

        ]
    }
}